package dev.tempo.domain.team;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;

/**
 * JPA entity for a team.
 *
 * Annotation rundown:
 *   @Entity       - Tells JPA this class maps to a table.
 *   @Table        - Names the table explicitly. Without it, JPA derives from class name.
 *   @Id / @GeneratedValue - Surrogate primary key, generated by Postgres' BIGSERIAL.
 *   @Column       - Maps a field to a column. Lets you set length, nullable, etc.
 *   @CreationTimestamp / @UpdateTimestamp - Hibernate-specific; populated automatically
 *                  on insert/update without touching the field manually.
 *
 * Lombok annotations:
 *   @Getter / @Setter - generates accessors at compile time.
 *   @NoArgsConstructor - required by JPA (it needs to instantiate via reflection).
 *   @AllArgsConstructor / @Builder - convenient for tests and seeding.
 *
 * Design note - entity vs DTO:
 *   This class is the ORM model and should NEVER be returned from controllers.
 *   Always map to TeamDto. Reasons:
 *     - Lazy loading can fail during JSON serialization if the session is closed
 *     - Internal fields (timestamps, version) shouldn't leak into the API contract
 *     - The API shape and DB shape will diverge over time; coupling them is painful
 */
@Entity
@Table(name = "team")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Team {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, unique = true, length = 64)
    private String name;

    @Column(nullable = false, unique = true, length = 8)
    private String abbreviation;

    @Column(nullable = false, length = 16)
    private String conference;

    @Column(nullable = false, length = 16)
    private String division;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;
}
